/**
 * This file is part of the BlockLotto core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

import React, { useEffect } from 'react';

const useScript = (url, key) => {
    useEffect(() => {
        const script = document.createElement('script');

        script.url = url;
        script.async = true;
        script.type = "text/javascript";

        if (key) {
            script["data-tokenization-key"] = key;
        }

        document.body.appendChild(script);

        return () => {
            document.body.removeChild(script);
        }
    }, [url]);
}

export default useScript;